name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Pre build
        run: |
          npm -v
          node -v
          npm ci
      - name: Build & Start
        run: |
          npm run build
          npm start
      - name: Run Test
        run: npm test
